ports:
  - port: 3005
    onOpen: ignore
  - port: 3306
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 8001
    onOpen: ignore
  - port: 8002
    onOpen: ignore
  - port: 9000
    onOpen: ignore
    visibility: private
  - port: 9009
    onOpen: ignore
    visibility: private
    
tasks:
  - name: Setup environment and launch
    init: |
      cp .env.example .env
      sed -i "s#APP_URL=http://127.0.0.1:8000#APP_URL=$(gp url 8000)#g" .env
      composer install --ignore-platform-reqs
      php artisan key:generate
      php artisan storage:link
      touch database/database.sqlite
      php artisan migrate:fresh
      php artisan db:seed
      npm i
      npm run build
      echo $(gp url 8000)
      php artisan serve
      

